# -*- coding: utf-8 -*-
"""
外研社三/四/五年级英语上下册完整单词数据
每条包含：单词、音标、中文、英文例句、中文例句、所属模块、类型、年级
"""

# ===== 三年级 =====
WORDS_3 = [
    # ===================== 上册 =====================
    # Module 1 - Hello! / Hi!
    {"id": 1, "module": "上0", "grade": "三年级", "word": "hello", "phonetic": "/həˈləʊ/", "chinese": "你好；喂", "type": "greeting", "example_en": "Hello! I'm Amy.", "example_cn": "你好！我是 Amy。"},
    {"id": 2, "module": "上0", "grade": "三年级", "word": "hi", "phonetic": "/haɪ/", "chinese": "你好（比 hello 更随意）", "type": "greeting", "example_en": "Hi! I'm Sam.", "example_cn": "你好！我是 Sam。"},
    {"id": 3, "module": "上0", "grade": "三年级", "word": "I'm", "phonetic": "/aɪm/", "chinese": "我是（I am 的缩写）", "type": "greeting", "example_en": "I'm Lingling.", "example_cn": "我是玲玲。"},
    {"id": 4, "module": "上0", "grade": "三年级", "word": "my", "phonetic": "/maɪ/", "chinese": "我的", "type": "pronoun", "example_en": "My name is Amy.", "example_cn": "我的名字叫 Amy。"},
    {"id": 5, "module": "上0", "grade": "三年级", "word": "name", "phonetic": "/neɪm/", "chinese": "名字", "type": "noun", "example_en": "What's your name?", "example_cn": "你叫什么名字？"},
    {"id": 6, "module": "上0", "grade": "三年级", "word": "what's", "phonetic": "/wɒts/", "chinese": "是什么（what is 缩写）", "type": "phrase", "example_en": "What's your name?", "example_cn": "你叫什么名字？"},
    {"id": 7, "module": "上0", "grade": "三年级", "word": "goodbye", "phonetic": "/ˌɡʊdˈbaɪ/", "chinese": "再见", "type": "greeting", "example_en": "Goodbye, Bobo!", "example_cn": "再见，Bobo！"},
    {"id": 8, "module": "上0", "grade": "三年级", "word": "have", "phonetic": "/hæv/", "chinese": "有；拥有", "type": "verb", "example_en": "Have a nice day!", "example_cn": "祝你今天愉快！"},
    {"id": 9, "module": "上0", "grade": "三年级", "word": "nice", "phonetic": "/naɪs/", "chinese": "令人愉快的；好的", "type": "adjective", "example_en": "Have a nice day!", "example_cn": "祝你今天愉快！"},
    {"id": 10, "module": "上0", "grade": "三年级", "word": "day", "phonetic": "/deɪ/", "chinese": "一天；白天", "type": "noun", "example_en": "Have a nice day!", "example_cn": "祝你今天愉快！"},
    {"id": 11, "module": "上0", "grade": "三年级", "word": "good morning", "phonetic": "/ˌɡʊd ˈmɔːnɪŋ/", "chinese": "早上好", "type": "greeting", "example_en": "Good morning, Ms Smart!", "example_cn": "早上好，Smart 老师！"},
    {"id": 12, "module": "上1", "grade": "三年级", "word": "friend", "phonetic": "/frend/", "chinese": "朋友", "type": "noun", "example_en": "Let's be friends!", "example_cn": "让我们做朋友吧！"},
    {"id": 13, "module": "上1", "grade": "三年级", "word": "let's", "phonetic": "/lets/", "chinese": "让我们（let us 缩写）", "type": "phrase", "example_en": "Let's play together!", "example_cn": "让我们一起玩吧！"},
    {"id": 14, "module": "上1", "grade": "三年级", "word": "be", "phonetic": "/biː/", "chinese": "是；成为", "type": "verb", "example_en": "Let's be friends!", "example_cn": "让我们做朋友吧！"},
    {"id": 15, "module": "上1", "grade": "三年级", "word": "nine", "phonetic": "/naɪn/", "chinese": "九；九个", "type": "number", "example_en": "I'm nine.", "example_cn": "我九岁。"},
    {"id": 16, "module": "上1", "grade": "三年级", "word": "twin", "phonetic": "/twɪn/", "chinese": "双胞胎之一", "type": "noun", "example_en": "We're twins!", "example_cn": "我们是双胞胎！"},
    {"id": 17, "module": "上1", "grade": "三年级", "word": "from", "phonetic": "/frɒm/", "chinese": "来自", "type": "preposition", "example_en": "We're from the UK.", "example_cn": "我们来自英国。"},
    {"id": 18, "module": "上1", "grade": "三年级", "word": "UK", "phonetic": "/ˌjuːˈkeɪ/", "chinese": "英国", "type": "noun", "example_en": "We're from the UK.", "example_cn": "我们来自英国。"},
    {"id": 19, "module": "上1", "grade": "三年级", "word": "play", "phonetic": "/pleɪ/", "chinese": "玩；玩耍", "type": "verb", "example_en": "Come and play!", "example_cn": "来一起玩吧！"},
    {"id": 20, "module": "上1", "grade": "三年级", "word": "come", "phonetic": "/kʌm/", "chinese": "来", "type": "verb", "example_en": "Come and play!", "example_cn": "来一起玩吧！"},
    {"id": 21, "module": "上1", "grade": "三年级", "word": "help", "phonetic": "/help/", "chinese": "帮助", "type": "verb", "example_en": "Let's help!", "example_cn": "让我们帮忙！"},
    {"id": 22, "module": "上1", "grade": "三年级", "word": "kite", "phonetic": "/kaɪt/", "chinese": "风筝", "type": "noun", "example_en": "My kite is in the tree.", "example_cn": "我的风筝在树上。"},
    {"id": 23, "module": "上1", "grade": "三年级", "word": "tree", "phonetic": "/triː/", "chinese": "树", "type": "noun", "example_en": "My kite is in the tree.", "example_cn": "我的风筝在树上。"},
    {"id": 24, "module": "上1", "grade": "三年级", "word": "thank you", "phonetic": "/ˈθæŋk juː/", "chinese": "谢谢", "type": "phrase", "example_en": "Thank you!", "example_cn": "谢谢！"},
    {"id": 25, "module": "上1", "grade": "三年级", "word": "here", "phonetic": "/hɪə/", "chinese": "这里", "type": "adverb", "example_en": "Here you are.", "example_cn": "给你。"},
    {"id": 26, "module": "上2", "grade": "三年级", "word": "school", "phonetic": "/skuːl/", "chinese": "学校", "type": "noun", "example_en": "What a nice school!", "example_cn": "好漂亮的学校！"},
    {"id": 27, "module": "上2", "grade": "三年级", "word": "schoolbag", "phonetic": "/ˈskuːlbæɡ/", "chinese": "书包", "type": "noun", "example_en": "It's my schoolbag.", "example_cn": "这是我的书包。"},
    {"id": 28, "module": "上2", "grade": "三年级", "word": "thing", "phonetic": "/θɪŋ/", "chinese": "东西；物品", "type": "noun", "example_en": "My school things.", "example_cn": "我的学习用品。"},
    {"id": 29, "module": "上2", "grade": "三年级", "word": "book", "phonetic": "/bʊk/", "chinese": "书", "type": "noun", "example_en": "A book and a pen.", "example_cn": "一本书和一支钢笔。"},
    {"id": 30, "module": "上2", "grade": "三年级", "word": "pen", "phonetic": "/pen/", "chinese": "钢笔", "type": "noun", "example_en": "It's a pen.", "example_cn": "这是一支钢笔。"},
    {"id": 31, "module": "上2", "grade": "三年级", "word": "pencil", "phonetic": "/ˈpensl/", "chinese": "铅笔", "type": "noun", "example_en": "It's a pencil.", "example_cn": "这是一支铅笔。"},
    {"id": 32, "module": "上2", "grade": "三年级", "word": "ruler", "phonetic": "/ˈruːlə/", "chinese": "尺子", "type": "noun", "example_en": "It's a ruler.", "example_cn": "这是一把尺子。"},
    {"id": 33, "module": "上2", "grade": "三年级", "word": "eraser", "phonetic": "/ɪˈreɪzə/", "chinese": "橡皮", "type": "noun", "example_en": "It's an eraser.", "example_cn": "这是一块橡皮。"},
    {"id": 34, "module": "上2", "grade": "三年级", "word": "pencil case", "phonetic": "/ˈpensl keɪs/", "chinese": "铅笔盒", "type": "noun", "example_en": "It's my pencil case.", "example_cn": "这是我的铅笔盒。"},
    {"id": 35, "module": "上2", "grade": "三年级", "word": "take care of", "phonetic": "/teɪk keər əv/", "chinese": "保管；照顾", "type": "phrase", "example_en": "Take care of your school things.", "example_cn": "保管好你的学习用品。"},
    {"id": 36, "module": "上2", "grade": "三年级", "word": "this", "phonetic": "/ðɪs/", "chinese": "这；这个", "type": "pronoun", "example_en": "What's this?", "example_cn": "这是什么？"},
    {"id": 37, "module": "上2", "grade": "三年级", "word": "that", "phonetic": "/ðæt/", "chinese": "那；那个", "type": "pronoun", "example_en": "What's that?", "example_cn": "那是什么？"},
    {"id": 38, "module": "上2", "grade": "三年级", "word": "whose", "phonetic": "/huːz/", "chinese": "谁的", "type": "pronoun", "example_en": "Whose pen is this?", "example_cn": "这是谁的钢笔？"},
    {"id": 39, "module": "上2", "grade": "三年级", "word": "your", "phonetic": "/jɔː/", "chinese": "你的；你们的", "type": "pronoun", "example_en": "Is this your pen?", "example_cn": "这是你的钢笔吗？"},
    {"id": 40, "module": "上3", "grade": "三年级", "word": "colourful", "phonetic": "/ˈkʌləfl/", "chinese": "五彩缤纷的", "type": "adjective", "example_en": "It's a colourful world!", "example_cn": "这是一个五彩缤纷的世界！"},
    {"id": 41, "module": "上3", "grade": "三年级", "word": "world", "phonetic": "/wɜːld/", "chinese": "世界", "type": "noun", "example_en": "It's a colourful world!", "example_cn": "这是一个五彩缤纷的世界！"},
    {"id": 42, "module": "上3", "grade": "三年级", "word": "colour", "phonetic": "/ˈkʌlə/", "chinese": "颜色", "type": "noun", "example_en": "What colour is it?", "example_cn": "它是什么颜色？"},
    {"id": 43, "module": "上3", "grade": "三年级", "word": "red", "phonetic": "/red/", "chinese": "红色的", "type": "adjective", "example_en": "It's red.", "example_cn": "它是红色的。"},
    {"id": 44, "module": "上3", "grade": "三年级", "word": "blue", "phonetic": "/bluː/", "chinese": "蓝色的", "type": "adjective", "example_en": "It's blue.", "example_cn": "它是蓝色的。"},
    {"id": 45, "module": "上3", "grade": "三年级", "word": "yellow", "phonetic": "/ˈjeləʊ/", "chinese": "黄色的", "type": "adjective", "example_en": "It's yellow.", "example_cn": "它是黄色的。"},
    {"id": 46, "module": "上3", "grade": "三年级", "word": "green", "phonetic": "/ɡriːn/", "chinese": "绿色的", "type": "adjective", "example_en": "It's green.", "example_cn": "它是绿色的。"},
    {"id": 47, "module": "上3", "grade": "三年级", "word": "pink", "phonetic": "/pɪŋk/", "chinese": "粉色的", "type": "adjective", "example_en": "It's pink.", "example_cn": "它是粉色的。"},
    {"id": 48, "module": "上3", "grade": "三年级", "word": "purple", "phonetic": "/ˈpɜːpl/", "chinese": "紫色的", "type": "adjective", "example_en": "It's purple.", "example_cn": "它是紫色的。"},
    {"id": 49, "module": "上3", "grade": "三年级", "word": "orange", "phonetic": "/ˈɒrɪndʒ/", "chinese": "橙色的", "type": "adjective", "example_en": "It's orange.", "example_cn": "它是橙色的。"},
    {"id": 50, "module": "上3", "grade": "三年级", "word": "balloon", "phonetic": "/bəˈluːn/", "chinese": "气球", "type": "noun", "example_en": "I want a balloon!", "example_cn": "我想要一个气球！"},
    {"id": 51, "module": "上3", "grade": "三年级", "word": "want", "phonetic": "/wɒnt/", "chinese": "想要", "type": "verb", "example_en": "I want a balloon!", "example_cn": "我想要一个气球！"},
    {"id": 52, "module": "上3", "grade": "三年级", "word": "rainbow", "phonetic": "/ˈreɪnbəʊ/", "chinese": "彩虹", "type": "noun", "example_en": "The rainbow is colourful.", "example_cn": "彩虹是五彩缤纷的。"},
    {"id": 53, "module": "上3", "grade": "三年级", "word": "umbrella", "phonetic": "/ʌmˈbrelə/", "chinese": "雨伞", "type": "noun", "example_en": "It's an umbrella.", "example_cn": "它是一把伞。"},
    {"id": 54, "module": "上3", "grade": "三年级", "word": "guess", "phonetic": "/ɡes/", "chinese": "猜", "type": "verb", "example_en": "Can you guess?", "example_cn": "你能猜吗？"},
    {"id": 55, "module": "上4", "grade": "三年级", "word": "fun", "phonetic": "/fʌn/", "chinese": "乐趣", "type": "noun", "example_en": "Fun with numbers.", "example_cn": "数字的乐趣。"},
    {"id": 56, "module": "上4", "grade": "三年级", "word": "number", "phonetic": "/ˈnʌmbə/", "chinese": "数字", "type": "noun", "example_en": "Fun with numbers.", "example_cn": "数字的乐趣。"},
    {"id": 57, "module": "上4", "grade": "三年级", "word": "one", "phonetic": "/wʌn/", "chinese": "一", "type": "number", "example_en": "One, two, three!", "example_cn": "一，二，三！"},
    {"id": 58, "module": "上4", "grade": "三年级", "word": "two", "phonetic": "/tuː/", "chinese": "二", "type": "number", "example_en": "One, two, three!", "example_cn": "一，二，三！"},
    {"id": 59, "module": "上4", "grade": "三年级", "word": "three", "phonetic": "/θriː/", "chinese": "三", "type": "number", "example_en": "One, two, three!", "example_cn": "一，二，三！"},
    {"id": 60, "module": "上4", "grade": "三年级", "word": "four", "phonetic": "/fɔː/", "chinese": "四", "type": "number", "example_en": "Four little babies.", "example_cn": "四只小宝宝。"},
    {"id": 61, "module": "上4", "grade": "三年级", "word": "five", "phonetic": "/faɪv/", "chinese": "五", "type": "number", "example_en": "Five, six, seven!", "example_cn": "五，六，七！"},
    {"id": 62, "module": "上4", "grade": "三年级", "word": "six", "phonetic": "/sɪks/", "chinese": "六", "type": "number", "example_en": "Five, six, seven!", "example_cn": "五，六，七！"},
    {"id": 63, "module": "上4", "grade": "三年级", "word": "seven", "phonetic": "/ˈsevn/", "chinese": "七", "type": "number", "example_en": "Five, six, seven!", "example_cn": "五，六，七！"},
    {"id": 64, "module": "上4", "grade": "三年级", "word": "eight", "phonetic": "/eɪt/", "chinese": "八", "type": "number", "example_en": "Eight, nine, ten!", "example_cn": "八，九，十！"},
    {"id": 65, "module": "上4", "grade": "三年级", "word": "nine", "phonetic": "/naɪn/", "chinese": "九", "type": "number", "example_en": "Eight, nine, ten!", "example_cn": "八，九，十！"},
    {"id": 66, "module": "上4", "grade": "三年级", "word": "ten", "phonetic": "/ten/", "chinese": "十", "type": "number", "example_en": "Eight, nine, ten!", "example_cn": "八，九，十！"},
    {"id": 67, "module": "上4", "grade": "三年级", "word": "eleven", "phonetic": "/ɪˈlevn/", "chinese": "十一", "type": "number", "example_en": "Eleven eggs.", "example_cn": "十一个蛋。"},
    {"id": 68, "module": "上4", "grade": "三年级", "word": "twelve", "phonetic": "/twelv/", "chinese": "十二", "type": "number", "example_en": "Twelve eggs.", "example_cn": "十二个蛋。"},
    {"id": 69, "module": "上4", "grade": "三年级", "word": "rope", "phonetic": "/rəʊp/", "chinese": "绳子", "type": "noun", "example_en": "How many ropes?", "example_cn": "有多少根绳子？"},
    {"id": 70, "module": "上4", "grade": "三年级", "word": "knot", "phonetic": "/nɒt/", "chinese": "结；中国结", "type": "noun", "example_en": "This is a Chinese knot.", "example_cn": "这是一个中国结。"},
    {"id": 71, "module": "上4", "grade": "三年级", "word": "beautiful", "phonetic": "/ˈbjuːtɪfl/", "chinese": "美丽的", "type": "adjective", "example_en": "It's beautiful.", "example_cn": "它很漂亮。"},
    {"id": 72, "module": "上4", "grade": "三年级", "word": "amazing", "phonetic": "/əˈmeɪzɪŋ/", "chinese": "令人惊奇的", "type": "adjective", "example_en": "That's amazing!", "example_cn": "太神奇了！"},
    {"id": 73, "module": "上4", "grade": "三年级", "word": "egg", "phonetic": "/eɡ/", "chinese": "蛋", "type": "noun", "example_en": "My twelve eggs!", "example_cn": "我的十二个蛋！"},
    {"id": 74, "module": "上5", "grade": "三年级", "word": "family", "phonetic": "/ˈfæməli/", "chinese": "家庭；家人", "type": "noun", "example_en": "We're family.", "example_cn": "我们是一家人。"},
    {"id": 75, "module": "上5", "grade": "三年级", "word": "sister", "phonetic": "/ˈsɪstə/", "chinese": "姐妹", "type": "noun", "example_en": "This is my sister.", "example_cn": "这是我的姐姐。"},
    {"id": 76, "module": "上5", "grade": "三年级", "word": "dad", "phonetic": "/dæd/", "chinese": "爸爸", "type": "noun", "example_en": "This is my dad.", "example_cn": "这是我的爸爸。"},
    {"id": 77, "module": "上5", "grade": "三年级", "word": "mum", "phonetic": "/mʌm/", "chinese": "妈妈", "type": "noun", "example_en": "This is my mum.", "example_cn": "这是我的妈妈。"},
    {"id": 78, "module": "上5", "grade": "三年级", "word": "grandma", "phonetic": "/ˈɡrænmɑː/", "chinese": "奶奶；外婆", "type": "noun", "example_en": "That's my grandma.", "example_cn": "那是我的奶奶。"},
    {"id": 79, "module": "上5", "grade": "三年级", "word": "grandpa", "phonetic": "/ˈɡrænpɑː/", "chinese": "爷爷；外公", "type": "noun", "example_en": "That's my grandpa.", "example_cn": "那是我的爷爷。"},
    {"id": 80, "module": "上5", "grade": "三年级", "word": "cap", "phonetic": "/kæp/", "chinese": "帽子", "type": "noun", "example_en": "Look at the cap!", "example_cn": "看那顶帽子！"},
    {"id": 81, "module": "上5", "grade": "三年级", "word": "worry", "phonetic": "/ˈwʌri/", "chinese": "担心", "type": "verb", "example_en": "Don't worry!", "example_cn": "别担心！"},
    {"id": 82, "module": "上5", "grade": "三年级", "word": "photo", "phonetic": "/ˈfəʊtəʊ/", "chinese": "照片", "type": "noun", "example_en": "Let's take a photo.", "example_cn": "我们拍张照片吧。"},
    {"id": 83, "module": "上5", "grade": "三年级", "word": "dog", "phonetic": "/dɒɡ/", "chinese": "狗", "type": "noun", "example_en": "Where's the dog?", "example_cn": "狗在哪里？"},
    {"id": 84, "module": "上5", "grade": "三年级", "word": "box", "phonetic": "/bɒks/", "chinese": "盒子", "type": "noun", "example_en": "It's in the orange box.", "example_cn": "它在橙色盒子里。"},
    {"id": 85, "module": "上5", "grade": "三年级", "word": "together", "phonetic": "/təˈɡeðə/", "chinese": "一起", "type": "adverb", "example_en": "Let's take a photo together.", "example_cn": "我们一起拍张照片吧。"},
    {"id": 86, "module": "上5", "grade": "三年级", "word": "dear", "phonetic": "/dɪə/", "chinese": "亲爱的", "type": "adjective", "example_en": "Dear little dog!", "example_cn": "亲爱的小狗！"},
    {"id": 87, "module": "上5", "grade": "三年级", "word": "little", "phonetic": "/ˈlɪtl/", "chinese": "小的", "type": "adjective", "example_en": "Dear little dog!", "example_cn": "亲爱的小狗！"},
    {"id": 88, "module": "上6", "grade": "三年级", "word": "home", "phonetic": "/həʊm/", "chinese": "家", "type": "noun", "example_en": "My sweet home.", "example_cn": "我甜蜜的家。"},
    {"id": 89, "module": "上6", "grade": "三年级", "word": "sweet", "phonetic": "/swiːt/", "chinese": "甜蜜的", "type": "adjective", "example_en": "My sweet home.", "example_cn": "我甜蜜的家。"},
    {"id": 90, "module": "上6", "grade": "三年级", "word": "where", "phonetic": "/weə/", "chinese": "在哪里", "type": "adverb", "example_en": "Where's Susu?", "example_cn": "Susu 在哪里？"},
    {"id": 91, "module": "上6", "grade": "三年级", "word": "living room", "phonetic": "/ˈlɪvɪŋ ruːm/", "chinese": "客厅", "type": "noun", "example_en": "She's in the living room.", "example_cn": "她在客厅。"},
    {"id": 92, "module": "上6", "grade": "三年级", "word": "chair", "phonetic": "/tʃeə/", "chinese": "椅子", "type": "noun", "example_en": "On the chair.", "example_cn": "在椅子上。"},
    {"id": 93, "module": "上6", "grade": "三年级", "word": "bedroom", "phonetic": "/ˈbedruːm/", "chinese": "卧室", "type": "noun", "example_en": "Look in the bedroom.", "example_cn": "在卧室里看看。"},
    {"id": 94, "module": "上6", "grade": "三年级", "word": "under", "phonetic": "/ˈʌndə/", "chinese": "在……下面", "type": "preposition", "example_en": "She's under the bed.", "example_cn": "她在床下。"},
    {"id": 95, "module": "上6", "grade": "三年级", "word": "bed", "phonetic": "/bed/", "chinese": "床", "type": "noun", "example_en": "She's under the bed.", "example_cn": "她在床下。"},
    {"id": 96, "module": "上6", "grade": "三年级", "word": "toy", "phonetic": "/tɔɪ/", "chinese": "玩具", "type": "noun", "example_en": "Susu's toy is here.", "example_cn": "Susu 的玩具在这里。"},
    {"id": 97, "module": "上6", "grade": "三年级", "word": "baby", "phonetic": "/ˈbeɪbi/", "chinese": "宝宝", "type": "noun", "example_en": "Four little babies!", "example_cn": "四只小宝宝！"},
    {"id": 98, "module": "上6", "grade": "三年级", "word": "kitchen", "phonetic": "/ˈkɪtʃɪn/", "chinese": "厨房", "type": "noun", "example_en": "Dad's in the kitchen.", "example_cn": "爸爸在厨房。"},
    {"id": 99, "module": "上6", "grade": "三年级", "word": "sun", "phonetic": "/sʌn/", "chinese": "太阳", "type": "noun", "example_en": "She loves the sun.", "example_cn": "她喜欢阳光。"},
    {"id": 100, "module": "上6", "grade": "三年级", "word": "run", "phonetic": "/rʌn/", "chinese": "跑", "type": "verb", "example_en": "He likes to run.", "example_cn": "他喜欢跑。"},
    {"id": 101, "module": "上6", "grade": "三年级", "word": "lucky", "phonetic": "/ˈlʌki/", "chinese": "幸运的", "type": "adjective", "example_en": "Lucky, lucky us!", "example_cn": "我们真幸运！"},
    {"id": 102, "module": "下1", "grade": "三年级", "word": "cute", "phonetic": "/kjuːt/",
     "chinese": "可爱的", "type": "adjective",
     "example_en": "The panda is cute.", "example_cn": "熊猫很可爱。"},
    {"id": 103, "module": "下1", "grade": "三年级", "word": "big", "phonetic": "/bɪɡ/",
     "chinese": "大的", "type": "adjective",
     "example_en": "The elephant is big.", "example_cn": "大象很大。"},
    {"id": 104, "module": "下1", "grade": "三年级", "word": "small", "phonetic": "/smɔːl/",
     "chinese": "小的", "type": "adjective",
     "example_en": "The mouse is small.", "example_cn": "老鼠很小。"},
    {"id": 105, "module": "下1", "grade": "三年级", "word": "thin", "phonetic": "/θɪn/",
     "chinese": "瘦的", "type": "adjective",
     "example_en": "The bird is thin.", "example_cn": "小鸟很瘦。"},
    {"id": 106, "module": "下1", "grade": "三年级", "word": "fat", "phonetic": "/fæt/",
     "chinese": "胖的", "type": "adjective",
     "example_en": "The pig is fat.", "example_cn": "猪很胖。"},
    {"id": 107, "module": "下1", "grade": "三年级", "word": "long", "phonetic": "/lɒŋ/",
     "chinese": "长的", "type": "adjective",
     "example_en": "The snake is long.", "example_cn": "蛇很长。"},
    {"id": 108, "module": "下1", "grade": "三年级", "word": "short", "phonetic": "/ʃɔːt/",
     "chinese": "短的/矮的", "type": "adjective",
     "example_en": "The rabbit has short ears.", "example_cn": "兔子有短短的耳朵。"},
    {"id": 109, "module": "下1", "grade": "三年级", "word": "tall", "phonetic": "/tɔːl/",
     "chinese": "高的", "type": "adjective",
     "example_en": "The giraffe is tall.", "example_cn": "长颈鹿很高。"},

    # Module 2 - This is the way I go to school
    {"id": 110, "module": "下2", "grade": "三年级", "word": "by", "phonetic": "/baɪ/",
     "chinese": "通过/乘坐", "type": "preposition",
     "example_en": "I go to school by bus.", "example_cn": "我乘公交车上学。"},
    {"id": 111, "module": "下2", "grade": "三年级", "word": "bus", "phonetic": "/bʌs/",
     "chinese": "公共汽车", "type": "noun",
     "example_en": "I go by bus.", "example_cn": "我坐公交车。"},
    {"id": 112, "module": "下2", "grade": "三年级", "word": "car", "phonetic": "/kɑː/",
     "chinese": "小汽车", "type": "noun",
     "example_en": "My dad drives a car.", "example_cn": "我爸爸开小汽车。"},
    {"id": 113, "module": "下2", "grade": "三年级", "word": "walk", "phonetic": "/wɔːk/",
     "chinese": "走路", "type": "verb",
     "example_en": "I go to school on foot.", "example_cn": "我走路去上学。"},
    {"id": 114, "module": "下2", "grade": "三年级", "word": "foot", "phonetic": "/fʊt/",
     "chinese": "脚", "type": "noun",
     "example_en": "I go to school on foot.", "example_cn": "我走路去上学。"},
    {"id": 115, "module": "下2", "grade": "三年级", "word": "school", "phonetic": "/skuːl/",
     "chinese": "学校", "type": "noun",
     "example_en": "I go to school.", "example_cn": "我去学校。"},
    {"id": 116, "module": "下2", "grade": "三年级", "word": "way", "phonetic": "/weɪ/",
     "chinese": "路/方式", "type": "noun",
     "example_en": "This is the way I go to school.", "example_cn": "这是我上学的路。"},

    # Module 3 - Today is Sunday
    {"id": 117, "module": "下3", "grade": "三年级", "word": "Sunday", "phonetic": "/ˈsʌndeɪ/",
     "chinese": "星期日", "type": "day",
     "example_en": "Today is Sunday.", "example_cn": "今天是星期日。"},
    {"id": 118, "module": "下3", "grade": "三年级", "word": "Monday", "phonetic": "/ˈmʌndeɪ/",
     "chinese": "星期一", "type": "day",
     "example_en": "Today is Monday.", "example_cn": "今天是星期一。"},
    {"id": 119, "module": "下3", "grade": "三年级", "word": "Saturday", "phonetic": "/ˈsætədeɪ/",
     "chinese": "星期六", "type": "day",
     "example_en": "I play football on Saturdays.", "example_cn": "我星期六踢足球。"},
    {"id": 120, "module": "下3", "grade": "三年级", "word": "today", "phonetic": "/təˈdeɪ/",
     "chinese": "今天", "type": "time",
     "example_en": "Today is Sunday.", "example_cn": "今天是星期日。"},
    {"id": 121, "module": "下3", "grade": "三年级", "word": "often", "phonetic": "/ˈɒfən/",
     "chinese": "经常", "type": "adverb",
     "example_en": "I often play football.", "example_cn": "我经常踢足球。"},
    {"id": 122, "module": "下3", "grade": "三年级", "word": "watch TV", "phonetic": "/wɒtʃ ˌtiːˈviː/",
     "chinese": "看电视", "type": "activity",
     "example_en": "I often watch TV on Sundays.", "example_cn": "我星期日常看电视。"},
    {"id": 123, "module": "下3", "grade": "三年级", "word": "read", "phonetic": "/riːd/",
     "chinese": "读", "type": "verb",
     "example_en": "I read books.", "example_cn": "我读书。"},

    # Module 4 - Do you like meat?
    {"id": 124, "module": "下4", "grade": "三年级", "word": "meat", "phonetic": "/miːt/",
     "chinese": "肉", "type": "food",
     "example_en": "Do you like meat?", "example_cn": "你喜欢肉吗？"},
    {"id": 125, "module": "下4", "grade": "三年级", "word": "fish", "phonetic": "/fɪʃ/",
     "chinese": "鱼", "type": "food",
     "example_en": "I don't like fish.", "example_cn": "我不喜欢鱼。"},
    {"id": 126, "module": "下4", "grade": "三年级", "word": "rice", "phonetic": "/raɪs/",
     "chinese": "米饭", "type": "food",
     "example_en": "I like rice.", "example_cn": "我喜欢米饭。"},
    {"id": 127, "module": "下4", "grade": "三年级", "word": "noodle", "phonetic": "/ˈnuːdl/",
     "chinese": "面条", "type": "food",
     "example_en": "I like noodles.", "example_cn": "我喜欢面条。"},
    {"id": 128, "module": "下4", "grade": "三年级", "word": "mango", "phonetic": "/ˈmæŋɡəʊ/",
     "chinese": "芒果", "type": "food",
     "example_en": "The mango is sweet.", "example_cn": "芒果很甜。"},
    {"id": 129, "module": "下4", "grade": "三年级", "word": "apple", "phonetic": "/ˈæpl/",
     "chinese": "苹果", "type": "food",
     "example_en": "I like apples.", "example_cn": "我喜欢苹果。"},
    {"id": 130, "module": "下4", "grade": "三年级", "word": "banana", "phonetic": "/bəˈnɑːnə/",
     "chinese": "香蕉", "type": "food",
     "example_en": "The banana is yellow.", "example_cn": "香蕉是黄色的。"},
    {"id": 131, "module": "下4", "grade": "三年级", "word": "orange", "phonetic": "/ˈɒrɪndʒ/",
     "chinese": "橙子", "type": "food",
     "example_en": "I like oranges.", "example_cn": "我喜欢橙子。"},

    # Module 5 - We fly kites in spring
    {"id": 132, "module": "下5", "grade": "三年级", "word": "spring", "phonetic": "/sprɪŋ/",
     "chinese": "春天", "type": "season",
     "example_en": "We fly kites in spring.", "example_cn": "我们在春天放风筝。"},
    {"id": 133, "module": "下5", "grade": "三年级", "word": "summer", "phonetic": "/ˈsʌmə/",
     "chinese": "夏天", "type": "season",
     "example_en": "It's hot in summer.", "example_cn": "夏天很热。"},
    {"id": 134, "module": "下5", "grade": "三年级", "word": "autumn", "phonetic": "/ˈɔːtəm/",
     "chinese": "秋天", "type": "season",
     "example_en": "The leaves fall in autumn.", "example_cn": "秋天树叶落下。"},
    {"id": 135, "module": "下5", "grade": "三年级", "word": "winter", "phonetic": "/ˈwɪntə/",
     "chinese": "冬天", "type": "season",
     "example_en": "It's cold in winter.", "example_cn": "冬天很冷。"},
    {"id": 136, "module": "下5", "grade": "三年级", "word": "kite", "phonetic": "/kaɪt/",
     "chinese": "风筝", "type": "noun",
     "example_en": "We fly kites in spring.", "example_cn": "我们在春天放风筝。"},
    {"id": 137, "module": "下5", "grade": "三年级", "word": "warm", "phonetic": "/wɔːm/",
     "chinese": "温暖的", "type": "adjective",
     "example_en": "It's warm in spring.", "example_cn": "春天很温暖。"},
    {"id": 138, "module": "下5", "grade": "三年级", "word": "hot", "phonetic": "/hɒt/",
     "chinese": "热的", "type": "adjective",
     "example_en": "It's hot in summer.", "example_cn": "夏天很热。"},
    {"id": 139, "module": "下5", "grade": "三年级", "word": "cool", "phonetic": "/kuːl/",
     "chinese": "凉爽的", "type": "adjective",
     "example_en": "It's cool in autumn.", "example_cn": "秋天很凉爽。"},
    {"id": 140, "module": "下5", "grade": "三年级", "word": "cold", "phonetic": "/kəʊld/",
     "chinese": "冷的", "type": "adjective",
     "example_en": "It's cold in winter.", "example_cn": "冬天很冷。"},

    # Module 6 - What do you do on Saturdays?
    {"id": 141, "module": "下6", "grade": "三年级", "word": "play football", "phonetic": "/pleɪ ˈfʊtbɔːl/",
     "chinese": "踢足球", "type": "activity",
     "example_en": "I play football on Saturdays.", "example_cn": "我星期六踢足球。"},
    {"id": 142, "module": "下6", "grade": "三年级", "word": "swim", "phonetic": "/swɪm/",
     "chinese": "游泳", "type": "activity",
     "example_en": "I can swim.", "example_cn": "我会游泳。"},
    {"id": 143, "module": "下6", "grade": "三年级", "word": "draw pictures", "phonetic": "/drɔː ˈpɪktʃəz/",
     "chinese": "画画", "type": "activity",
     "example_en": "I draw pictures on Sundays.", "example_cn": "我星期日画画。"},
    {"id": 144, "module": "下6", "grade": "三年级", "word": "computer game", "phonetic": "/kəmˈpjuːtə ɡeɪm/",
     "chinese": "电脑游戏", "type": "activity",
     "example_en": "I play computer games.", "example_cn": "我玩电脑游戏。"},
    {"id": 145, "module": "下6", "grade": "三年级", "word": "music", "phonetic": "/ˈmjuːzɪk/",
     "chinese": "音乐", "type": "noun",
     "example_en": "I like music.", "example_cn": "我喜欢音乐。"},
    {"id": 146, "module": "下6", "grade": "三年级", "word": "sleep", "phonetic": "/sliːp/",
     "chinese": "睡觉", "type": "activity",
     "example_en": "I sleep at nine.", "example_cn": "我九点睡觉。"},

    # Module 7 - We have a big family
    {"id": 147, "module": "下7", "grade": "三年级", "word": "family", "phonetic": "/ˈfæməli/",
     "chinese": "家庭", "type": "noun",
     "example_en": "We have a big family.", "example_cn": "我们有一个大家庭。"},
    {"id": 148, "module": "下7", "grade": "三年级", "word": "mother", "phonetic": "/ˈmʌðə/",
     "chinese": "妈妈", "type": "family",
     "example_en": "This is my mother.", "example_cn": "这是我妈妈。"},
    {"id": 149, "module": "下7", "grade": "三年级", "word": "father", "phonetic": "/ˈfɑːðə/",
     "chinese": "爸爸", "type": "family",
     "example_en": "My father is a doctor.", "example_cn": "我爸爸是医生。"},
    {"id": 150, "module": "下7", "grade": "三年级", "word": "brother", "phonetic": "/ˈbrʌðə/",
     "chinese": "哥哥/弟弟", "type": "family",
     "example_en": "I have a brother.", "example_cn": "我有一个哥哥/弟弟。"},
    {"id": 151, "module": "下7", "grade": "三年级", "word": "sister", "phonetic": "/ˈsɪstə/",
     "chinese": "姐姐/妹妹", "type": "family",
     "example_en": "I have a sister.", "example_cn": "我有一个姐姐/妹妹。"},
    {"id": 152, "module": "下7", "grade": "三年级", "word": "grandmother", "phonetic": "/ˈɡrænmʌðə/",
     "chinese": "奶奶/外婆", "type": "family",
     "example_en": "My grandmother cooks well.", "example_cn": "我奶奶做饭很好吃。"},
    {"id": 153, "module": "下7", "grade": "三年级", "word": "grandfather", "phonetic": "/ˈɡrænfɑːðə/",
     "chinese": "爷爷/外公", "type": "family",
     "example_en": "My grandfather is tall.", "example_cn": "我爷爷很高。"},

    # Module 8 - We can see the stars
    {"id": 154, "module": "下8", "grade": "三年级", "word": "star", "phonetic": "/stɑː/",
     "chinese": "星星", "type": "noun",
     "example_en": "We can see the stars at night.", "example_cn": "我们晚上能看见星星。"},
    {"id": 155, "module": "下8", "grade": "三年级", "word": "moon", "phonetic": "/muːn/",
     "chinese": "月亮", "type": "noun",
     "example_en": "The moon is round tonight.", "example_cn": "今晚月亮是圆的。"},
    {"id": 156, "module": "下8", "grade": "三年级", "word": "night", "phonetic": "/naɪt/",
     "chinese": "夜晚", "type": "time",
     "example_en": "Good night!", "example_cn": "晚安！"},
    {"id": 157, "module": "下8", "grade": "三年级", "word": "see", "phonetic": "/siː/",
     "chinese": "看见", "type": "verb",
     "example_en": "I can see the stars.", "example_cn": "我能看见星星。"},
    {"id": 158, "module": "下8", "grade": "三年级", "word": "can", "phonetic": "/kæn/",
     "chinese": "会/能", "type": "verb",
     "example_en": "I can swim.", "example_cn": "我会游泳。"},
    {"id": 159, "module": "下8", "grade": "三年级", "word": "sky", "phonetic": "/skaɪ/",
     "chinese": "天空", "type": "noun",
     "example_en": "The sky is blue.", "example_cn": "天空是蓝色的。"},
    {"id": 160, "module": "下8", "grade": "三年级", "word": "sun", "phonetic": "/sʌn/",
     "chinese": "太阳", "type": "noun",
     "example_en": "The sun is bright.", "example_cn": "太阳很明亮。"},

    # Module 9 - I had a good time
    {"id": 161, "module": "下9", "grade": "三年级", "word": "time", "phonetic": "/taɪm/",
     "chinese": "时光", "type": "noun",
     "example_en": "I had a good time.", "example_cn": "我玩得很开心。"},
    {"id": 162, "module": "下9", "grade": "三年级", "word": "good", "phonetic": "/ɡʊd/",
     "chinese": "好的", "type": "adjective",
     "example_en": "I had a good time.", "example_cn": "我玩得很开心。"},
    {"id": 163, "module": "下9", "grade": "三年级", "word": "happy", "phonetic": "/ˈhæpi/",
     "chinese": "开心的", "type": "adjective",
     "example_en": "I was happy at the party.", "example_cn": "我在派对上很开心。"},
    {"id": 164, "module": "下9", "grade": "三年级", "word": "sad", "phonetic": "/sæd/",
     "chinese": "伤心的", "type": "adjective",
     "example_en": "I was sad yesterday.", "example_cn": "我昨天很伤心。"},
    {"id": 165, "module": "下9", "grade": "三年级", "word": "party", "phonetic": "/ˈpɑːti/",
     "chinese": "聚会", "type": "noun",
     "example_en": "We had a birthday party.", "example_cn": "我们举办了一个生日聚会。"},
    {"id": 166, "module": "下9", "grade": "三年级", "word": "was", "phonetic": "/wɒz/",
     "chinese": "是（过去式，单数）", "type": "verb",
     "example_en": "I was happy.", "example_cn": "我很开心。"},
    {"id": 167, "module": "下9", "grade": "三年级", "word": "were", "phonetic": "/wɜː/",
     "chinese": "是（过去式，复数）", "type": "verb",
     "example_en": "They were very happy.", "example_cn": "他们很开心。"},

    # Module 10 - It's a sunny day
    {"id": 168, "module": "下10", "grade": "三年级", "word": "sunny", "phonetic": "/ˈsʌni/",
     "chinese": "阳光明媚的", "type": "adjective",
     "example_en": "It's a sunny day.", "example_cn": "今天是晴天。"},
    {"id": 169, "module": "下10", "grade": "三年级", "word": "rainy", "phonetic": "/ˈreɪni/",
     "chinese": "下雨的", "type": "adjective",
     "example_en": "It's rainy today.", "example_cn": "今天下雨。"},
    {"id": 170, "module": "下10", "grade": "三年级", "word": "snowy", "phonetic": "/ˈsnəʊi/",
     "chinese": "下雪的", "type": "adjective",
     "example_en": "It's snowy in winter.", "example_cn": "冬天下雪。"},
    {"id": 171, "module": "下10", "grade": "三年级", "word": "windy", "phonetic": "/ˈwɪndi/",
     "chinese": "有风的", "type": "adjective",
     "example_en": "It's windy today.", "example_cn": "今天有风。"},
    {"id": 172, "module": "下10", "grade": "三年级", "word": "cloudy", "phonetic": "/ˈklaʊdi/",
     "chinese": "多云的", "type": "adjective",
     "example_en": "It's cloudy today.", "example_cn": "今天多云。"},
    {"id": 173, "module": "下10", "grade": "三年级", "word": "weather", "phonetic": "/ˈweðə/",
     "chinese": "天气", "type": "noun",
     "example_en": "What's the weather like?", "example_cn": "天气怎么样？"},
    {"id": 174, "module": "下10", "grade": "三年级", "word": "rain", "phonetic": "/reɪn/",
     "chinese": "雨", "type": "noun",
     "example_en": "The rain is heavy.", "example_cn": "雨很大。"},
    {"id": 175, "module": "下10", "grade": "三年级", "word": "wind", "phonetic": "/wɪnd/",
     "chinese": "风", "type": "noun",
     "example_en": "The wind is strong.", "example_cn": "风很大。"},
]

# ===== 四年级 =====
WORDS_4 = [
    # ===================== 上册 =====================
    # Module 1 - I went to Sanya for my holidays
    {"id": 176, "module": "四上1", "grade": "四年级", "word": "holiday", "phonetic": "/ˈhɒlədeɪ/",
     "chinese": "假期", "type": "noun",
     "example_en": "I went to Sanya for my holidays.", "example_cn": "我去三亚度假了。"},
    {"id": 177, "module": "四上1", "grade": "四年级", "word": "went", "phonetic": "/went/",
     "chinese": "去（go的过去式）", "type": "verb",
     "example_en": "I went to Sanya.", "example_cn": "我去了三亚。"},
    {"id": 178, "module": "四上1", "grade": "四年级", "word": "Sanya", "phonetic": "/ˈsænjə/",
     "chinese": "三亚", "type": "place",
     "example_en": "I went to Sanya.", "example_cn": "我去了三亚。"},
    {"id": 179, "module": "四上1", "grade": "四年级", "word": "swim", "phonetic": "/swɪm/",
     "chinese": "游泳", "type": "verb",
     "example_en": "I swam in the sea.", "example_cn": "我在海里游泳了。"},
    {"id": 180, "module": "四上1", "grade": "四年级", "word": "sea", "phonetic": "/siː/",
     "chinese": "海", "type": "noun",
     "example_en": "I swam in the sea.", "example_cn": "我在海里游泳了。"},
    {"id": 181, "module": "四上1", "grade": "四年级", "word": "beach", "phonetic": "/biːtʃ/",
     "chinese": "海滩", "type": "noun",
     "example_en": "We played on the beach.", "example_cn": "我们在海滩上玩耍。"},
    {"id": 182, "module": "四上1", "grade": "四年级", "word": "last", "phonetic": "/lɑːst/",
     "chinese": "上一个的", "type": "adjective",
     "example_en": "Where did you go last weekend?", "example_cn": "你上周末去哪了？"},
    {"id": 183, "module": "四上1", "grade": "四年级", "word": "weekend", "phonetic": "/wiːkˈend/",
     "chinese": "周末", "type": "noun",
     "example_en": "I visited my grandparents last weekend.", "example_cn": "我上周末去看望了祖父母。"},
    {"id": 184, "module": "四上1", "grade": "四年级", "word": "visit", "phonetic": "/ˈvɪzɪt/",
     "chinese": "参观/看望", "type": "verb",
     "example_en": "I visited the Great Wall.", "example_cn": "我游览了长城。"},
    {"id": 185, "module": "四上1", "grade": "四年级", "word": "Great Wall", "phonetic": "/ɡreɪt wɔːl/",
     "chinese": "长城", "type": "place",
     "example_en": "I visited the Great Wall.", "example_cn": "我游览了长城。"},

    # Module 2 - Grandparents are special
    {"id": 186, "module": "四上2", "grade": "四年级", "word": "special", "phonetic": "/ˈspeʃəl/",
     "chinese": "特别的", "type": "adjective",
     "example_en": "Grandparents are special.", "example_cn": "祖父母是特别的。"},
    {"id": 187, "module": "四上2", "grade": "四年级", "word": "kind", "phonetic": "/kaɪnd/",
     "chinese": "慈祥的/善良的", "type": "adjective",
     "example_en": "My grandmother is very kind.", "example_cn": "我奶奶非常慈祥。"},
    {"id": 188, "module": "四上2", "grade": "四年级", "word": "grandparent", "phonetic": "/ˈɡrænpeərənt/",
     "chinese": "祖父母", "type": "family",
     "example_en": "My grandparents live with us.", "example_cn": "我的祖父母和我们住在一起。"},
    {"id": 189, "module": "四上2", "grade": "四年级", "word": "story", "phonetic": "/ˈstɔːri/",
     "chinese": "故事", "type": "noun",
     "example_en": "He tells me stories every night.", "example_cn": "他每天晚上给我讲故事。"},
    {"id": 190, "module": "四上2", "grade": "四年级", "word": "tall", "phonetic": "/tɔːl/",
     "chinese": "高的", "type": "adjective",
     "example_en": "He is so tall!", "example_cn": "他好高啊！"},
    {"id": 191, "module": "四上2", "grade": "四年级", "word": "every", "phonetic": "/ˈevri/",
     "chinese": "每个", "type": "adjective",
     "example_en": "He comes here every day.", "example_cn": "他每天都来这里。"},

    # Module 3 - My weekend was great!
    {"id": 192, "module": "四上3", "grade": "四年级", "word": "great", "phonetic": "/ɡreɪt/",
     "chinese": "很棒的", "type": "adjective",
     "example_en": "My weekend was great!", "example_cn": "我周末很棒！"},
    {"id": 193, "module": "四上3", "grade": "四年级", "word": "mountain", "phonetic": "/ˈmaʊntɪn/",
     "chinese": "山", "type": "noun",
     "example_en": "The mountain is very high.", "example_cn": "山很高。"},
    {"id": 194, "module": "四上3", "grade": "四年级", "word": "did", "phonetic": "/dɪd/",
     "chinese": "做（do的过去式）", "type": "verb",
     "example_en": "Did you have a good time?", "example_cn": "你玩得开心吗？"},
    {"id": 195, "module": "四上3", "grade": "四年级", "word": "take", "phonetic": "/teɪk/",
     "chinese": "拿/乘坐", "type": "verb",
     "example_en": "We took many photos.", "example_cn": "我们拍了很多照片。"},
    {"id": 196, "module": "四上3", "grade": "四年级", "word": "photo", "phonetic": "/ˈfəʊtəʊ/",
     "chinese": "照片", "type": "noun",
     "example_en": "I took a photo of the mountain.", "example_cn": "我给山拍了张照片。"},
    {"id": 197, "module": "四上3", "grade": "四年级", "word": "climb", "phonetic": "/klaɪm/",
     "chinese": "爬", "type": "verb",
     "example_en": "We climbed the mountain.", "example_cn": "我们爬了山。"},

    # Module 4 - I got a letter from my pen pal
    {"id": 198, "module": "四上4", "grade": "四年级", "word": "letter", "phonetic": "/ˈletə/",
     "chinese": "信", "type": "noun",
     "example_en": "I got a letter from my pen pal.", "example_cn": "我收到了笔友的来信。"},
    {"id": 199, "module": "四上4", "grade": "四年级", "word": "pen pal", "phonetic": "/pen pæl/",
     "chinese": "笔友", "type": "noun",
     "example_en": "I have a pen pal in London.", "example_cn": "我在伦敦有一个笔友。"},
    {"id": 200, "module": "四上4", "grade": "四年级", "word": "London", "phonetic": "/ˈlʌndən/",
     "chinese": "伦敦", "type": "place",
     "example_en": "My pen pal lives in London.", "example_cn": "我的笔友住在伦敦。"},
    {"id": 201, "module": "四上4", "grade": "四年级", "word": "Tower Bridge", "phonetic": "/ˈtaʊə brɪdʒ/",
     "chinese": "塔桥（伦敦）", "type": "place",
     "example_en": "She visited Tower Bridge last week.", "example_cn": "她上周游览了塔桥。"},
    {"id": 202, "module": "四上4", "grade": "四年级", "word": "got", "phonetic": "/ɡɒt/",
     "chinese": "收到（get的过去式）", "type": "verb",
     "example_en": "I got a letter yesterday.", "example_cn": "我昨天收到了一封信。"},

    # Module 5 - Our school is beautiful
    {"id": 203, "module": "四上5", "grade": "四年级", "word": "beautiful", "phonetic": "/ˈbjuːtɪfəl/",
     "chinese": "美丽的", "type": "adjective",
     "example_en": "Our school is beautiful.", "example_cn": "我们的学校很美丽。"},
    {"id": 204, "module": "四上5", "grade": "四年级", "word": "love", "phonetic": "/lʌv/",
     "chinese": "爱/热爱", "type": "verb",
     "example_en": "We love our school.", "example_cn": "我们热爱我们的学校。"},
    {"id": 205, "module": "四上5", "grade": "四年级", "word": "computer room", "phonetic": "/kəmˈpjuːtə ruːm/",
     "chinese": "电脑室", "type": "place",
     "example_en": "There is a computer room in our school.", "example_cn": "我们学校有电脑室。"},
    {"id": 206, "module": "四上5", "grade": "四年级", "word": "library", "phonetic": "/ˈlaɪbrəri/",
     "chinese": "图书馆", "type": "place",
     "example_en": "I like reading in the library.", "example_cn": "我喜欢在图书馆读书。"},
    {"id": 207, "module": "四上5", "grade": "四年级", "word": "gym", "phonetic": "/dʒɪm/",
     "chinese": "体育馆", "type": "place",
     "example_en": "We have PE in the gym.", "example_cn": "我们在体育馆上体育课。"},

    # Module 6 - We wish you a Merry Christmas!
    {"id": 208, "module": "四上6", "grade": "四年级", "word": "Merry Christmas", "phonetic": "/ˈmeri ˈkrɪsməs/",
     "chinese": "圣诞快乐", "type": "greeting",
     "example_en": "We wish you a Merry Christmas!", "example_cn": "我们祝你圣诞快乐！"},
    {"id": 209, "module": "四上6", "grade": "四年级", "word": "wish", "phonetic": "/wɪʃ/",
     "chinese": "祝愿", "type": "verb",
     "example_en": "We wish you happiness.", "example_cn": "我们祝你幸福。"},
    {"id": 210, "module": "四上6", "grade": "四年级", "word": "Christmas", "phonetic": "/ˈkrɪsməs/",
     "chinese": "圣诞节", "type": "holiday",
     "example_en": "Merry Christmas!", "example_cn": "圣诞快乐！"},
    {"id": 211, "module": "四上6", "grade": "四年级", "word": "present", "phonetic": "/ˈprezənt/",
     "chinese": "礼物", "type": "noun",
     "example_en": "I got many Christmas presents.", "example_cn": "我收到了很多圣诞礼物。"},
    {"id": 212, "module": "四上6", "grade": "四年级", "word": "turkey", "phonetic": "/ˈtɜːki/",
     "chinese": "火鸡", "type": "food",
     "example_en": "We eat turkey on Christmas Day.", "example_cn": "圣诞节我们吃火鸡。"},
    {"id": 213, "module": "四上6", "grade": "四年级", "word": "dinner", "phonetic": "/ˈdɪnə/",
     "chinese": "晚餐", "type": "noun",
     "example_en": "We have a big dinner on Christmas.", "example_cn": "圣诞节我们吃大餐。"},

    # Module 7 - I'll send you a postcard
    {"id": 214, "module": "四上7", "grade": "四年级", "word": "send", "phonetic": "/send/",
     "chinese": "发送/寄", "type": "verb",
     "example_en": "I'll send you a postcard.", "example_cn": "我会给你寄一张明信片。"},
    {"id": 215, "module": "四上7", "grade": "四年级", "word": "postcard", "phonetic": "/ˈpəʊstkɑːd/",
     "chinese": "明信片", "type": "noun",
     "example_en": "I sent a postcard from Shanghai.", "example_cn": "我从上海寄了一张明信片。"},
    {"id": 216, "module": "四上7", "grade": "四年级", "word": "Shanghai", "phonetic": "/ˌʃæŋˈhaɪ/",
     "chinese": "上海", "type": "place",
     "example_en": "I'm going to Shanghai.", "example_cn": "我要去上海。"},
    {"id": 217, "module": "四上7", "grade": "四年级", "word": "dear", "phonetic": "/dɪə/",
     "chinese": "亲爱的", "type": "adjective",
     "example_en": "Dear friend, how are you?", "example_cn": "亲爱的朋友，你好吗？"},
    {"id": 218, "module": "四上7", "grade": "四年级", "word": "idea", "phonetic": "/aɪˈdɪə/",
     "chinese": "主意", "type": "noun",
     "example_en": "That's a great idea!", "example_cn": "这是个好主意！"},

    # Module 8 - The Pandas are in danger
    {"id": 219, "module": "四上8", "grade": "四年级", "word": "danger", "phonetic": "/ˈdeɪndʒə/",
     "chinese": "危险", "type": "noun",
     "example_en": "Pandas are in danger.", "example_cn": "熊猫处于危险之中。"},
    {"id": 220, "module": "四上8", "grade": "四年级", "word": "protect", "phonetic": "/prəˈtekt/",
     "chinese": "保护", "type": "verb",
     "example_en": "We must protect the animals.", "example_cn": "我们必须保护动物。"},
    {"id": 221, "module": "四上8", "grade": "四年级", "word": "panda", "phonetic": "/ˈpændə/",
     "chinese": "熊猫", "type": "animal",
     "example_en": "The panda is from China.", "example_cn": "熊猫来自中国。"},
    {"id": 222, "module": "四上8", "grade": "四年级", "word": "bamboo", "phonetic": "/bæmˈbuː/",
     "chinese": "竹子", "type": "noun",
     "example_en": "Pandas eat bamboo.", "example_cn": "熊猫吃竹子。"},
    {"id": 223, "module": "四上8", "grade": "四年级", "word": "animal", "phonetic": "/ˈænɪməl/",
     "chinese": "动物", "type": "noun",
     "example_en": "We must protect wild animals.", "example_cn": "我们必须保护野生动物。"},

    # Module 9 - I was happy yesterday
    {"id": 224, "module": "四上9", "grade": "四年级", "word": "yesterday", "phonetic": "/ˈjestədeɪ/",
     "chinese": "昨天", "type": "time",
     "example_en": "I was happy yesterday.", "example_cn": "我昨天很开心。"},
    {"id": 225, "module": "四上9", "grade": "四年级", "word": "excited", "phonetic": "/ɪkˈsaɪtɪd/",
     "chinese": "兴奋的", "type": "adjective",
     "example_en": "I was excited about the trip.", "example_cn": "我对这次旅行感到兴奋。"},
    {"id": 226, "module": "四上9", "grade": "四年级", "word": "tired", "phonetic": "/ˈtaɪəd/",
     "chinese": "累的", "type": "adjective",
     "example_en": "I was tired after the long walk.", "example_cn": "走了很长路之后我很累。"},
    {"id": 227, "module": "四上9", "grade": "四年级", "word": "angry", "phonetic": "/ˈæŋɡri/",
     "chinese": "生气的", "type": "adjective",
     "example_en": "He was angry with me.", "example_cn": "他生我的气了。"},
    {"id": 228, "module": "四上9", "grade": "四年级", "word": "felt", "phonetic": "/felt/",
     "chinese": "感觉（feel的过去式）", "type": "verb",
     "example_en": "I felt happy yesterday.", "example_cn": "我昨天感到开心。"},

    # Module 10 - I'm in New York now
    {"id": 229, "module": "四上10", "grade": "四年级", "word": "New York", "phonetic": "/njuː jɔːk/",
     "chinese": "纽约", "type": "place",
     "example_en": "I'm in New York now.", "example_cn": "我现在在纽约。"},
    {"id": 230, "module": "四上10", "grade": "四年级", "word": "city", "phonetic": "/ˈsɪti/",
     "chinese": "城市", "type": "noun",
     "example_en": "New York is a big city.", "example_cn": "纽约是个大城市。"},
    {"id": 231, "module": "四上10", "grade": "四年级", "word": "weather", "phonetic": "/ˈweðə/",
     "chinese": "天气", "type": "noun",
     "example_en": "What's the weather like?", "example_cn": "天气怎么样？"},
    {"id": 232, "module": "四上10", "grade": "四年级", "word": "sunny", "phonetic": "/ˈsʌni/",
     "chinese": "阳光明媚的", "type": "adjective",
     "example_en": "It's sunny but cold.", "example_cn": "阳光明媚但很冷。"},
    {"id": 233, "module": "四上10", "grade": "四年级", "word": "cool", "phonetic": "/kuːl/",
     "chinese": "凉爽的", "type": "adjective",
     "example_en": "It's cool in New York.", "example_cn": "纽约很凉爽。"},

    # ===================== 下册 =====================
    # Module 1 - I helped Mum
    {"id": 234, "module": "四下1", "grade": "四年级", "word": "help", "phonetic": "/help/",
     "chinese": "帮助", "type": "verb",
     "example_en": "I helped Mum cook dinner.", "example_cn": "我帮妈妈做晚饭。"},
    {"id": 235, "module": "四下1", "grade": "四年级", "word": "cook", "phonetic": "/kʊk/",
     "chinese": "烹饪/做饭", "type": "verb",
     "example_en": "Mum cooks dinner every day.", "example_cn": "妈妈每天做晚饭。"},
    {"id": 236, "module": "四下1", "grade": "四年级", "word": "dinner", "phonetic": "/ˈdɪnə/",
     "chinese": "晚餐/正餐", "type": "noun",
     "example_en": "We have dinner at 6 o'clock.", "example_cn": "我们六点吃晚饭。"},
    {"id": 237, "module": "四下1", "grade": "四年级", "word": "yesterday", "phonetic": "/ˈjestədeɪ/",
     "chinese": "昨天", "type": "time",
     "example_en": "I helped Mum yesterday.", "example_cn": "我昨天帮妈妈了。"},
    {"id": 238, "module": "四下1", "grade": "四年级", "word": "wash", "phonetic": "/wɒʃ/",
     "chinese": "洗", "type": "verb",
     "example_en": "I wash my clothes on Sundays.", "example_cn": "我星期日洗衣服。"},
    {"id": 239, "module": "四下1", "grade": "四年级", "word": "clothes", "phonetic": "/kləʊðz/",
     "chinese": "衣服", "type": "noun",
     "example_en": "These are my clothes.", "example_cn": "这些是我的衣服。"},

    # Module 2 - I made a cake
    {"id": 240, "module": "四下2", "grade": "四年级", "word": "make", "phonetic": "/meɪk/",
     "chinese": "制作", "type": "verb",
     "example_en": "I made a cake for Mum.", "example_cn": "我给妈妈做了蛋糕。"},
    {"id": 241, "module": "四下2", "grade": "四年级", "word": "cake", "phonetic": "/keɪk/",
     "chinese": "蛋糕", "type": "food",
     "example_en": "The cake is delicious.", "example_cn": "蛋糕很好吃。"},
    {"id": 242, "module": "四下2", "grade": "四年级", "word": "birthday", "phonetic": "/ˈbɜːθdeɪ/",
     "chinese": "生日", "type": "noun",
     "example_en": "It's Mum's birthday today.", "example_cn": "今天是妈妈的生日。"},
    {"id": 243, "module": "四下2", "grade": "四年级", "word": "delicious", "phonetic": "/dɪˈlɪʃəs/",
     "chinese": "美味的", "type": "adjective",
     "example_en": "The cake is delicious.", "example_cn": "蛋糕很好吃。"},

    # Module 3 - They were very happy
    {"id": 244, "module": "四下3", "grade": "四年级", "word": "Children's Day", "phonetic": "/ˈtʃɪldrənz deɪ/",
     "chinese": "儿童节", "type": "holiday",
     "example_en": "They were happy on Children's Day.", "example_cn": "他们在儿童节很开心。"},
    {"id": 245, "module": "四下3", "grade": "四年级", "word": "clown", "phonetic": "/klaʊn/",
     "chinese": "小丑", "type": "noun",
     "example_en": "The clown made us laugh.", "example_cn": "小丑让我们大笑。"},
    {"id": 246, "module": "四下3", "grade": "四年级", "word": "laugh", "phonetic": "/lɑːf/",
     "chinese": "笑", "type": "verb",
     "example_en": "The clown made us laugh.", "example_cn": "小丑让我们大笑。"},

    # Module 4 - We are going to have a picnic
    {"id": 247, "module": "四下4", "grade": "四年级", "word": "picnic", "phonetic": "/ˈpɪknɪk/",
     "chinese": "野餐", "type": "activity",
     "example_en": "We are going to have a picnic.", "example_cn": "我们要去野餐。"},
    {"id": 248, "module": "四下4", "grade": "四年级", "word": "Saturday", "phonetic": "/ˈsætədeɪ/",
     "chinese": "星期六", "type": "day",
     "example_en": "We'll have a picnic this Saturday.", "example_cn": "这周六我们要去野餐。"},
    {"id": 249, "module": "四下4", "grade": "四年级", "word": "park", "phonetic": "/pɑːk/",
     "chinese": "公园", "type": "place",
     "example_en": "We'll go to the park.", "example_cn": "我们要去公园。"},
    {"id": 250, "module": "四下4", "grade": "四年级", "word": "lake", "phonetic": "/leɪk/",
     "chinese": "湖", "type": "place",
     "example_en": "There is a lake near the park.", "example_cn": "公园附近有一个湖。"},

    # Module 5 - I'll be a scientist
    {"id": 251, "module": "四下5", "grade": "四年级", "word": "scientist", "phonetic": "/ˈsaɪəntɪst/",
     "chinese": "科学家", "type": "job",
     "example_en": "I'll be a scientist.", "example_cn": "我要当科学家。"},
    {"id": 252, "module": "四下5", "grade": "四年级", "word": "grow up", "phonetic": "/ɡrəʊ ʌp/",
     "chinese": "长大", "type": "verb",
     "example_en": "What will you be when you grow up?", "example_cn": "你长大后要当什么？"},
    {"id": 253, "module": "四下5", "grade": "四年级", "word": "engineer", "phonetic": "/ˌendʒɪˈnɪə/",
     "chinese": "工程师", "type": "job",
     "example_en": "My father is an engineer.", "example_cn": "我爸爸是工程师。"},
    {"id": 254, "module": "四下5", "grade": "四年级", "word": "driver", "phonetic": "/ˈdraɪvə/",
     "chinese": "司机", "type": "job",
     "example_en": "My uncle is a bus driver.", "example_cn": "我叔叔是公交车司机。"},
    {"id": 255, "module": "四下5", "grade": "四年级", "word": "teacher", "phonetic": "/ˈtiːtʃə/",
     "chinese": "老师", "type": "job",
     "example_en": "I want to be a teacher.", "example_cn": "我想当老师。"},

    # Module 6 - We wish you a happy Children's Day
    {"id": 256, "module": "四下6", "grade": "四年级", "word": "Children's Day", "phonetic": "/ˈtʃɪldrənz deɪ/",
     "chinese": "儿童节", "type": "holiday",
     "example_en": "Happy Children's Day!", "example_cn": "儿童节快乐！"},
    {"id": 257, "module": "四下6", "grade": "四年级", "word": "flower", "phonetic": "/ˈflaʊə/",
     "chinese": "花", "type": "noun",
     "example_en": "I gave Mum a flower.", "example_cn": "我给妈妈一朵花。"},
    {"id": 258, "module": "四下6", "grade": "四年级", "word": "glove", "phonetic": "/ɡlʌv/",
     "chinese": "手套", "type": "noun",
     "example_en": "These gloves are warm.", "example_cn": "这双手套很暖和。"},

    # Module 7 - I helped the old man
    {"id": 259, "module": "四下7", "grade": "四年级", "word": "cross", "phonetic": "/krɒs/",
     "chinese": "穿过", "type": "verb",
     "example_en": "I helped the old man cross the road.", "example_cn": "我帮助老人过马路。"},
    {"id": 260, "module": "四下7", "grade": "四年级", "word": "road", "phonetic": "/rəʊd/",
     "chinese": "马路/道路", "type": "noun",
     "example_en": "Be careful on the road.", "example_cn": "路上要小心。"},
    {"id": 261, "module": "四下7", "grade": "四年级", "word": "old man", "phonetic": "/əʊld mæn/",
     "chinese": "老人", "type": "noun",
     "example_en": "I helped the old man.", "example_cn": "我帮助了老人。"},

    # Module 8 - He is very clever
    {"id": 262, "module": "四下8", "grade": "四年级", "word": "clever", "phonetic": "/ˈklevə/",
     "chinese": "聪明的", "type": "adjective",
     "example_en": "He is very clever.", "example_cn": "他非常聪明。"},
    {"id": 263, "module": "四下8", "grade": "四年级", "word": "solve", "phonetic": "/sɒlv/",
     "chinese": "解决", "type": "verb",
     "example_en": "He can solve hard problems.", "example_cn": "他能解决难题。"},
    {"id": 264, "module": "四下8", "grade": "四年级", "word": "problem", "phonetic": "/ˈprɒbləm/",
     "chinese": "问题", "type": "noun",
     "example_en": "I have a math problem.", "example_cn": "我有一道数学题。"},
    {"id": 265, "module": "四下8", "grade": "四年级", "word": "answer", "phonetic": "/ˈɑːnsə/",
     "chinese": "答案", "type": "noun",
     "example_en": "What is the answer?", "example_cn": "答案是什么？"},

    # Module 9 - We were on holiday
    {"id": 266, "module": "四下9", "grade": "四年级", "word": "holiday", "phonetic": "/ˈhɒlədeɪ/",
     "chinese": "假期/度假", "type": "noun",
     "example_en": "We were on holiday in Hainan.", "example_cn": "我们在海南度假。"},
    {"id": 267, "module": "四下9", "grade": "四年级", "word": "Hainan", "phonetic": "/haɪˈnɑːn/",
     "chinese": "海南", "type": "place",
     "example_en": "Hainan is very beautiful.", "example_cn": "海南很美。"},
    {"id": 268, "module": "四下9", "grade": "四年级", "word": "July", "phonetic": "/dʒuˈlaɪ/",
     "chinese": "七月", "type": "month",
     "example_en": "We went to Hainan last July.", "example_cn": "我们去年七月去了海南。"},

    # Module 10 - The world is beautiful
    {"id": 269, "module": "四下10", "grade": "四年级", "word": "world", "phonetic": "/wɜːld/",
     "chinese": "世界", "type": "noun",
     "example_en": "The world is beautiful.", "example_cn": "世界很美丽。"},
    {"id": 270, "module": "四下10", "grade": "四年级", "word": "beautiful", "phonetic": "/ˈbjuːtɪfəl/",
     "chinese": "美丽的", "type": "adjective",
     "example_en": "The world is beautiful.", "example_cn": "世界很美丽。"},
    {"id": 271, "module": "四下10", "grade": "四年级", "word": "should", "phonetic": "/ʃʊd/",
     "chinese": "应该", "type": "modal",
     "example_en": "We should protect the world.", "example_cn": "我们应该保护世界。"},
    {"id": 272, "module": "四下10", "grade": "四年级", "word": "learn", "phonetic": "/lɜːn/",
     "chinese": "学习", "type": "verb",
     "example_en": "We should learn more.", "example_cn": "我们应该多学习。"},
]

# ===== 五年级 =====
WORDS_5 = [
    # ===================== 上册 =====================
    # Module 1 - There are only nineteen crayons
    {"id": 273, "module": "五上1", "grade": "五年级", "word": "nineteen", "phonetic": "/naɪnˈtiːn/",
     "chinese": "十九", "type": "number",
     "example_en": "There are only nineteen crayons.", "example_cn": "只有十九支蜡笔。"},
    {"id": 274, "module": "五上1", "grade": "五年级", "word": "crayon", "phonetic": "/ˈkreɪən/",
     "chinese": "蜡笔", "type": "noun",
     "example_en": "I have nineteen crayons.", "example_cn": "我有十九支蜡笔。"},
    {"id": 275, "module": "五上1", "grade": "五年级", "word": "only", "phonetic": "/ˈəʊnli/",
     "chinese": "仅仅/只有", "type": "adverb",
     "example_en": "There are only three apples.", "example_cn": "只有三个苹果。"},
    {"id": 276, "module": "五上1", "grade": "五年级", "word": "twenty", "phonetic": "/ˈtwenti/",
     "chinese": "二十", "type": "number",
     "example_en": "There were twenty yesterday.", "example_cn": "昨天有二十支。"},
    {"id": 277, "module": "五上1", "grade": "五年级", "word": "thirty", "phonetic": "/ˈθɜːti/",
     "chinese": "三十", "type": "number",
     "example_en": "There are thirty students.", "example_cn": "有三十个学生。"},
    {"id": 278, "module": "五上1", "grade": "五年级", "word": "forty", "phonetic": "/ˈfɔːti/",
     "chinese": "四十", "type": "number",
     "example_en": "The book has forty pages.", "example_cn": "这本书有四十页。"},
    {"id": 279, "module": "五上1", "grade": "五年级", "word": "missing", "phonetic": "/ˈmɪsɪŋ/",
     "chinese": "不见的/丢失的", "type": "adjective",
     "example_en": "Where is the missing one?", "example_cn": "少的那个去哪了？"},
    {"id": 280, "module": "五上1", "grade": "五年级", "word": "were", "phonetic": "/wɜː/",
     "chinese": "是（are的过去式）", "type": "verb",
     "example_en": "There were twenty yesterday.", "example_cn": "昨天有二十支。"},

    # Module 2 - We bought ice creams
    {"id": 281, "module": "五上2", "grade": "五年级", "word": "bought", "phonetic": "/bɔːt/",
     "chinese": "买（buy的过去式）", "type": "verb",
     "example_en": "We bought ice creams yesterday.", "example_cn": "昨天我们买了冰淇淋。"},
    {"id": 282, "module": "五上2", "grade": "五年级", "word": "ice cream", "phonetic": "/aɪs kriːm/",
     "chinese": "冰淇淋", "type": "food",
     "example_en": "We bought ice creams.", "example_cn": "我们买了冰淇淋。"},
    {"id": 283, "module": "五上2", "grade": "五年级", "word": "strawberry", "phonetic": "/ˈstrɔːbəri/",
     "chinese": "草莓", "type": "food",
     "example_en": "I like strawberry ice cream.", "example_cn": "我喜欢草莓冰淇淋。"},
    {"id": 284, "module": "五上2", "grade": "五年级", "word": "chocolate", "phonetic": "/ˈtʃɒklət/",
     "chinese": "巧克力", "type": "food",
     "example_en": "I like chocolate ice cream.", "example_cn": "我喜欢巧克力冰淇淋。"},
    {"id": 285, "module": "五上2", "grade": "五年级", "word": "flavour", "phonetic": "/ˈfleɪvə/",
     "chinese": "口味", "type": "noun",
     "example_en": "What flavour did you buy?", "example_cn": "你买了什么口味的？"},
    {"id": 286, "module": "五上2", "grade": "五年级", "word": "afternoon", "phonetic": "/ˌɑːftəˈnuːn/",
     "chinese": "下午", "type": "time",
     "example_en": "Yesterday afternoon, we went to the park.", "example_cn": "昨天下午我们去了公园。"},

    # Module 3 - My father was a fisherman
    {"id": 287, "module": "五上3", "grade": "五年级", "word": "fisherman", "phonetic": "/ˈfɪʃəmən/",
     "chinese": "渔夫", "type": "job",
     "example_en": "My father was a fisherman.", "example_cn": "我爸爸以前是渔夫。"},
    {"id": 288, "module": "五上3", "grade": "五年级", "word": "cook", "phonetic": "/kʊk/",
     "chinese": "厨师", "type": "job",
     "example_en": "He is a cook now.", "example_cn": "他现在是个厨师。"},
    {"id": 289, "module": "五上3", "grade": "五年级", "word": "worker", "phonetic": "/ˈwɜːkə/",
     "chinese": "工人", "type": "job",
     "example_en": "My mother is a factory worker.", "example_cn": "我妈妈是工厂工人。"},
    {"id": 290, "module": "五上3", "grade": "五年级", "word": "doctor", "phonetic": "/ˈdɒktə/",
     "chinese": "医生", "type": "job",
     "example_en": "My aunt is a doctor.", "example_cn": "我阿姨是医生。"},
    {"id": 291, "module": "五上3", "grade": "五年级", "word": "nurse", "phonetic": "/nɜːs/",
     "chinese": "护士", "type": "job",
     "example_en": "The nurse is very kind.", "example_cn": "护士很善良。"},
    {"id": 292, "module": "五上3", "grade": "五年级", "word": "taxi driver", "phonetic": "/ˈtæksi ˈdraɪvə/",
     "chinese": "出租车司机", "type": "job",
     "example_en": "His father is a taxi driver.", "example_cn": "他爸爸是出租车司机。"},
    {"id": 293, "module": "五上3", "grade": "五年级", "word": "businessman", "phonetic": "/ˈbɪznəsmæn/",
     "chinese": "商人", "type": "job",
     "example_en": "My uncle is a businessman.", "example_cn": "我叔叔是商人。"},
    {"id": 294, "module": "五上3", "grade": "五年级", "word": "wife", "phonetic": "/waɪf/",
     "chinese": "妻子", "type": "family",
     "example_en": "His wife is a teacher.", "example_cn": "他的妻子是老师。"},
    {"id": 295, "module": "五上3", "grade": "五年级", "word": "grow up", "phonetic": "/ɡrəʊ ʌp/",
     "chinese": "长大", "type": "verb",
     "example_en": "What do you want to be when you grow up?", "example_cn": "你长大后想当什么？"},

    # Module 4 - We didn't see the Pandas
    {"id": 296, "module": "五上4", "grade": "五年级", "word": "didn't", "phonetic": "/ˈdɪdənt/",
     "chinese": "没有（did not）", "type": "verb",
     "example_en": "We didn't see the Pandas.", "example_cn": "我们没有看到熊猫。"},
    {"id": 297, "module": "五上4", "grade": "五年级", "word": "zoo", "phonetic": "/zuː/",
     "chinese": "动物园", "type": "place",
     "example_en": "We went to the zoo last Sunday.", "example_cn": "我们上周日去了动物园。"},
    {"id": 298, "module": "五上4", "grade": "五年级", "word": "elephant", "phonetic": "/ˈelɪfənt/",
     "chinese": "大象", "type": "animal",
     "example_en": "The elephant is very big.", "example_cn": "大象非常大。"},
    {"id": 299, "module": "五上4", "grade": "五年级", "word": "giraffe", "phonetic": "/dʒɪˈrɑːf/",
     "chinese": "长颈鹿", "type": "animal",
     "example_en": "The giraffe has a long neck.", "example_cn": "长颈鹿脖子很长。"},
    {"id": 300, "module": "五上4", "grade": "五年级", "word": "lion", "phonetic": "/ˈlaɪən/",
     "chinese": "狮子", "type": "animal",
     "example_en": "The lion is the king of the forest.", "example_cn": "狮子是森林之王。"},
    {"id": 301, "module": "五上4", "grade": "五年级", "word": "monkey", "phonetic": "/ˈmʌŋki/",
     "chinese": "猴子", "type": "animal",
     "example_en": "The monkey is climbing the tree.", "example_cn": "猴子正在爬树。"},

    # Module 5 - Dad always puts the rubbish in the bin
    {"id": 302, "module": "五上5", "grade": "五年级", "word": "rubbish", "phonetic": "/ˈrʌbɪʃ/",
     "chinese": "垃圾", "type": "noun",
     "example_en": "Don't throw the rubbish on the ground.", "example_cn": "不要把垃圾扔在地上。"},
    {"id": 303, "module": "五上5", "grade": "五年级", "word": "bin", "phonetic": "/bɪn/",
     "chinese": "垃圾桶", "type": "noun",
     "example_en": "Put the rubbish in the bin.", "example_cn": "把垃圾放进垃圾桶。"},
    {"id": 304, "module": "五上5", "grade": "五年级", "word": "always", "phonetic": "/ˈɔːlweɪz/",
     "chinese": "总是", "type": "adverb",
     "example_en": "Dad always puts the rubbish in the bin.", "example_cn": "爸爸总是把垃圾放进垃圾桶。"},
    {"id": 305, "module": "五上5", "grade": "五年级", "word": "put", "phonetic": "/pʊt/",
     "chinese": "放", "type": "verb",
     "example_en": "Please put the book on the desk.", "example_cn": "请把书放在桌子上。"},
    {"id": 306, "module": "五上5", "grade": "五年级", "word": "paper", "phonetic": "/ˈpeɪpə/",
     "chinese": "纸", "type": "noun",
     "example_en": "Don't throw paper on the ground.", "example_cn": "不要把纸扔在地上。"},
    {"id": 307, "module": "五上5", "grade": "五年级", "word": "pick up", "phonetic": "/pɪk ʌp/",
     "chinese": "捡起", "type": "verb",
     "example_en": "Please pick up the rubbish.", "example_cn": "请把垃圾捡起来。"},
    {"id": 308, "module": "五上5", "grade": "五年级", "word": "throw", "phonetic": "/θrəʊ/",
     "chinese": "扔", "type": "verb",
     "example_en": "Don't throw rubbish.", "example_cn": "不要乱扔垃圾。"},

    # Module 6 - I am reading a newspaper
    {"id": 309, "module": "五上6", "grade": "五年级", "word": "newspaper", "phonetic": "/ˈnjuːzpeɪpə/",
     "chinese": "报纸", "type": "noun",
     "example_en": "I am reading a newspaper.", "example_cn": "我在看报纸。"},
    {"id": 310, "module": "五上6", "grade": "五年级", "word": "magazine", "phonetic": "/ˌmæɡəˈziːn/",
     "chinese": "杂志", "type": "noun",
     "example_en": "I read a magazine every week.", "example_cn": "我每周读一本杂志。"},
    {"id": 311, "module": "五上6", "grade": "五年级", "word": "article", "phonetic": "/ˈɑːtɪkəl/",
     "chinese": "文章", "type": "noun",
     "example_en": "I read an interesting article.", "example_cn": "我读了一篇有趣的文章。"},
    {"id": 312, "module": "五上6", "grade": "五年级", "word": "news", "phonetic": "/njuːz/",
     "chinese": "新闻", "type": "noun",
     "example_en": "Is there any good news?", "example_cn": "有什么好新闻吗？"},
    {"id": 313, "module": "五上6", "grade": "五年级", "word": "quiet", "phonetic": "/ˈkwaɪət/",
     "chinese": "安静的", "type": "adjective",
     "example_en": "Please be quiet in the library.", "example_cn": "请在图书馆保持安静。"},
    {"id": 314, "module": "五上6", "grade": "五年级", "word": "study", "phonetic": "/ˈstʌdi/",
     "chinese": "学习", "type": "verb",
     "example_en": "I am studying English.", "example_cn": "我在学英语。"},

    # Module 7 - There are five people in my family
    {"id": 315, "module": "五上7", "grade": "五年级", "word": "people", "phonetic": "/ˈpiːpəl/",
     "chinese": "人们", "type": "noun",
     "example_en": "There are five people in my family.", "example_cn": "我家有五口人。"},
    {"id": 316, "module": "五上7", "grade": "五年级", "word": "grandparents", "phonetic": "/ˈɡrænpeərənts/",
     "chinese": "祖父母", "type": "family",
     "example_en": "I live with my grandparents.", "example_cn": "我和祖父母住在一起。"},
    {"id": 317, "module": "五上7", "grade": "五年级", "word": "cousin", "phonetic": "/ˈkʌzən/",
     "chinese": "堂/表兄弟姐妹", "type": "family",
     "example_en": "My cousin is my aunt's child.", "example_cn": "我的表/堂兄弟姐妹是姑姑的孩子。"},
    {"id": 318, "module": "五上7", "grade": "五年级", "word": "aunt", "phonetic": "/ɑːnt/",
     "chinese": "姑姑/阿姨", "type": "family",
     "example_en": "My aunt is a teacher.", "example_cn": "我姑姑是老师。"},
    {"id": 319, "module": "五上7", "grade": "五年级", "word": "uncle", "phonetic": "/ˈʌŋkəl/",
     "chinese": "叔叔/舅舅", "type": "family",
     "example_en": "My uncle works in Shanghai.", "example_cn": "我叔叔在上海工作。"},
    {"id": 320, "module": "五上7", "grade": "五年级", "word": "baby", "phonetic": "/ˈbeɪbi/",
     "chinese": "婴儿", "type": "family",
     "example_en": "The baby is sleeping.", "example_cn": "宝宝在睡觉。"},

    # Module 8 - I'm making a cake
    {"id": 321, "module": "五上8", "grade": "五年级", "word": "making", "phonetic": "/ˈmeɪkɪŋ/",
     "chinese": "正在制作", "type": "verb",
     "example_en": "I'm making a cake.", "example_cn": "我正在做蛋糕。"},
    {"id": 322, "module": "五上8", "grade": "五年级", "word": "ingredient", "phonetic": "/ɪnˈɡriːdiənt/",
     "chinese": "配料/原料", "type": "noun",
     "example_en": "What are the ingredients?", "example_cn": "有哪些配料？"},
    {"id": 323, "module": "五上8", "grade": "五年级", "word": "flour", "phonetic": "/ˈflaʊə/",
     "chinese": "面粉", "type": "food",
     "example_en": "We need flour to make a cake.", "example_cn": "做蛋糕需要面粉。"},
    {"id": 324, "module": "五上8", "grade": "五年级", "word": "sugar", "phonetic": "/ˈʃʊɡə/",
     "chinese": "糖", "type": "food",
     "example_en": "Too much sugar is not good.", "example_cn": "太多糖不好。"},
    {"id": 325, "module": "五上8", "grade": "五年级", "word": "egg", "phonetic": "/eɡ/",
     "chinese": "鸡蛋", "type": "food",
     "example_en": "I need two eggs.", "example_cn": "我需要两个鸡蛋。"},
    {"id": 326, "module": "五上8", "grade": "五年级", "word": "butter", "phonetic": "/ˈbʌtə/",
     "chinese": "黄油", "type": "food",
     "example_en": "Add some butter to the cake.", "example_cn": "往蛋糕里加点黄油。"},
    {"id": 327, "module": "五上8", "grade": "五年级", "word": "kitchen", "phonetic": "/ˈkɪtʃɪn/",
     "chinese": "厨房", "type": "place",
     "example_en": "Mum is in the kitchen.", "example_cn": "妈妈在厨房。"},

    # Module 9 - Are you feeling sad?
    {"id": 328, "module": "五上9", "grade": "五年级", "word": "feeling", "phonetic": "/ˈfiːlɪŋ/",
     "chinese": "感觉", "type": "noun",
     "example_en": "Are you feeling sad?", "example_cn": "你难过吗？"},
    {"id": 329, "module": "五上9", "grade": "五年级", "word": "excited", "phonetic": "/ɪkˈsaɪtɪd/",
     "chinese": "兴奋的", "type": "adjective",
     "example_en": "I'm feeling excited! Tomorrow is the sports day.", "example_cn": "我感到兴奋！明天是运动会。"},
    {"id": 330, "module": "五上9", "grade": "五年级", "word": "bored", "phonetic": "/bɔːd/",
     "chinese": "无聊的", "type": "adjective",
     "example_en": "I'm feeling bored.", "example_cn": "我感到无聊。"},
    {"id": 331, "module": "五上9", "grade": "五年级", "word": "worried", "phonetic": "/ˈwʌrɪd/",
     "chinese": "担心的", "type": "adjective",
     "example_en": "I'm worried about the exam.", "example_cn": "我担心考试。"},
    {"id": 332, "module": "五上9", "grade": "五年级", "word": "happy", "phonetic": "/ˈhæpi/",
     "chinese": "开心的", "type": "adjective",
     "example_en": "I'm feeling happy today.", "example_cn": "我今天很开心。"},
    {"id": 333, "module": "五上9", "grade": "五年级", "word": "angry", "phonetic": "/ˈæŋɡri/",
     "chinese": "生气的", "type": "adjective",
     "example_en": "Are you feeling angry?", "example_cn": "你在生气吗？"},
    {"id": 334, "module": "五上9", "grade": "五年级", "word": "scared", "phonetic": "/skeəd/",
     "chinese": "害怕的", "type": "adjective",
     "example_en": "I'm feeling scared.", "example_cn": "我感到害怕。"},
    {"id": 335, "module": "五上9", "grade": "五年级", "word": "nervous", "phonetic": "/ˈnɜːvəs/",
     "chinese": "紧张的", "type": "adjective",
     "example_en": "I'm feeling nervous before the test.", "example_cn": "考试前我感到紧张。"},

    # Module 10 - I'm watching TV
    {"id": 336, "module": "五上10", "grade": "五年级", "word": "programme", "phonetic": "/ˈprəʊɡræm/",
     "chinese": "节目", "type": "noun",
     "example_en": "What programme is on TV?", "example_cn": "电视上有什么节目？"},
    {"id": 337, "module": "五上10", "grade": "五年级", "word": "cartoon", "phonetic": "/kɑːˈtuːn/",
     "chinese": "卡通/动画片", "type": "noun",
     "example_en": "I like watching cartoons.", "example_cn": "我喜欢看动画片。"},
    {"id": 338, "module": "五上10", "grade": "五年级", "word": "documentary", "phonetic": "/ˌdɒkjʊˈmentəri/",
     "chinese": "纪录片", "type": "noun",
     "example_en": "I watched a nature documentary.", "example_cn": "我看了一部自然纪录片。"},
    {"id": 339, "module": "五上10", "grade": "五年级", "word": "news", "phonetic": "/njuːz/",
     "chinese": "新闻", "type": "noun",
     "example_en": "I watch the news every evening.", "example_cn": "我每天晚上看新闻。"},
    {"id": 340, "module": "五上10", "grade": "五年级", "word": "game show", "phonetic": "/ɡeɪm ʃəʊ/",
     "chinese": "游戏节目", "type": "noun",
     "example_en": "My favourite programme is a game show.", "example_cn": "我最喜欢的节目是游戏节目。"},

    # ===================== 下册 =====================
    # Module 1 - He is playing the piano
    {"id": 341, "module": "五下1", "grade": "五年级", "word": "piano", "phonetic": "/piˈænəʊ/",
     "chinese": "钢琴", "type": "noun",
     "example_en": "He is playing the piano.", "example_cn": "他正在弹钢琴。"},
    {"id": 342, "module": "五下1", "grade": "五年级", "word": "violin", "phonetic": "/ˌvaɪəˈlɪn/",
     "chinese": "小提琴", "type": "noun",
     "example_en": "She is playing the violin.", "example_cn": "她正在拉小提琴。"},
    {"id": 343, "module": "五下1", "grade": "五年级", "word": "guitar", "phonetic": "/ɡɪˈtɑː/",
     "chinese": "吉他", "type": "noun",
     "example_en": "I am playing the guitar.", "example_cn": "我正在弹吉他。"},
    {"id": 344, "module": "五下1", "grade": "五年级", "word": "drum", "phonetic": "/drʌm/",
     "chinese": "鼓", "type": "noun",
     "example_en": "The children are playing drums.", "example_cn": "孩子们在打鼓。"},
    {"id": 345, "module": "五下1", "grade": "五年级", "word": "beautifully", "phonetic": "/ˈbjuːtɪfəli/",
     "chinese": "优美地", "type": "adverb",
     "example_en": "He is playing the piano beautifully.", "example_cn": "他正在优美地弹钢琴。"},
    {"id": 346, "module": "五下1", "grade": "五年级", "word": "listen", "phonetic": "/ˈlɪsən/",
     "chinese": "听", "type": "verb",
     "example_en": "Listen! The music is beautiful.", "example_cn": "听！音乐很美。"},

    # Module 2 - She learnt English last year
    {"id": 347, "module": "五下2", "grade": "五年级", "word": "learnt", "phonetic": "/lɜːnt/",
     "chinese": "学习（learn的过去式）", "type": "verb",
     "example_en": "She learnt English last year.", "example_cn": "她去年学了英语。"},
    {"id": 348, "module": "五下2", "grade": "五年级", "word": "last year", "phonetic": "/lɑːst jɪə/",
     "chinese": "去年", "type": "time",
     "example_en": "I went to Beijing last year.", "example_cn": "我去年去了北京。"},
    {"id": 349, "module": "五下2", "grade": "五年级", "word": "dancer", "phonetic": "/ˈdɑːnsə/",
     "chinese": "舞者/舞蹈家", "type": "job",
     "example_en": "She wants to be a dancer.", "example_cn": "她想当舞蹈家。"},
    {"id": 350, "module": "五下2", "grade": "五年级", "word": "actor", "phonetic": "/ˈæktə/",
     "chinese": "演员", "type": "job",
     "example_en": "My brother is an actor.", "example_cn": "我哥哥是演员。"},
    {"id": 351, "module": "五下2", "grade": "五年级", "word": "year", "phonetic": "/jɪə/",
     "chinese": "年", "type": "noun",
     "example_en": "There are twelve months in a year.", "example_cn": "一年有十二个月。"},

    # Module 3 - We had a good time
    {"id": 352, "module": "五下3", "grade": "五年级", "word": "time", "phonetic": "/taɪm/",
     "chinese": "时光/时光", "type": "noun",
     "example_en": "We had a good time at the picnic!", "example_cn": "我们在野餐中玩得很开心！"},
    {"id": 353, "module": "五下3", "grade": "五年级", "word": "laugh", "phonetic": "/lɑːf/",
     "chinese": "笑", "type": "verb",
     "example_en": "We all laughed at the party.", "example_cn": "我们在派对上都笑了。"},
    {"id": 354, "module": "五下3", "grade": "五年级", "word": "nothing", "phonetic": "/ˈnʌθɪŋ/",
     "chinese": "什么都没有", "type": "pronoun",
     "example_en": "We did nothing today.", "example_cn": "我们今天什么都没做。"},

    # Module 4 - I'll send you a card
    {"id": 355, "module": "五下4", "grade": "五年级", "word": "send", "phonetic": "/send/",
     "chinese": "发送/寄", "type": "verb",
     "example_en": "I'll send you a card from London.", "example_cn": "我会从伦敦给你寄一张卡片。"},
    {"id": 356, "module": "五下4", "grade": "五年级", "word": "London", "phonetic": "/ˈlʌndən/",
     "chinese": "伦敦", "type": "place",
     "example_en": "I'm visiting London.", "example_cn": "我在游览伦敦。"},

    # Module 5 - It's a sunny day
    {"id": 357, "module": "五下5", "grade": "五年级", "word": "beach", "phonetic": "/biːtʃ/",
     "chinese": "海滩", "type": "place",
     "example_en": "Let's go to the beach!", "example_cn": "我们去海滩吧！"},
    {"id": 358, "module": "五下5", "grade": "五年级", "word": "sunny", "phonetic": "/ˈsʌni/",
     "chinese": "阳光明媚的", "type": "adjective",
     "example_en": "It's a sunny day.", "example_cn": "今天是晴天。"},
    {"id": 359, "module": "五下5", "grade": "五年级", "word": "rainy", "phonetic": "/ˈreɪni/",
     "chinese": "下雨的", "type": "adjective",
     "example_en": "It's rainy today.", "example_cn": "今天下雨。"},
    {"id": 360, "module": "五下5", "grade": "五年级", "word": "cloudy", "phonetic": "/ˈklaʊdi/",
     "chinese": "多云的", "type": "adjective",
     "example_en": "It's cloudy today.", "example_cn": "今天多云。"},

    # Module 6 - We are going to learn English
    {"id": 361, "module": "五下6", "grade": "五年级", "word": "term", "phonetic": "/tɜːm/",
     "chinese": "学期", "type": "noun",
     "example_en": "We are going to learn English next term.", "example_cn": "下学期我们将学英语。"},
    {"id": 362, "module": "五下6", "grade": "五年级", "word": "next", "phonetic": "/nekst/",
     "chinese": "下一个的", "type": "adjective",
     "example_en": "Next week is the holiday.", "example_cn": "下周是假期。"},
    {"id": 363, "module": "五下6", "grade": "五年级", "word": "subject", "phonetic": "/ˈsʌbdʒɪkt/",
     "chinese": "学科", "type": "noun",
     "example_en": "My favourite subject is English.", "example_cn": "我最喜欢的学科是英语。"},
    {"id": 364, "module": "五下6", "grade": "五年级", "word": "maths", "phonetic": "/mæθs/",
     "chinese": "数学", "type": "subject",
     "example_en": "I am good at maths.", "example_cn": "我数学很好。"},
    {"id": 365, "module": "五下6", "grade": "五年级", "word": "science", "phonetic": "/ˈsaɪəns/",
     "chinese": "科学", "type": "subject",
     "example_en": "We have science on Tuesdays.", "example_cn": "我们星期二有科学课。"},
    {"id": 366, "module": "五下6", "grade": "五年级", "word": "PE", "phonetic": "/ˌpiːˈiː/",
     "chinese": "体育", "type": "subject",
     "example_en": "We have PE on Fridays.", "example_cn": "我们星期五有体育课。"},

    # Module 7 - There are many animals
    {"id": 367, "module": "五下7", "grade": "五年级", "word": "many", "phonetic": "/ˈmeni/",
     "chinese": "许多", "type": "adjective",
     "example_en": "There are many animals in the zoo.", "example_cn": "动物园里有许多动物。"},
    {"id": 368, "module": "五下7", "grade": "五年级", "word": "zookeeper", "phonetic": "/ˈzuːkiːpə/",
     "chinese": "动物园管理员", "type": "job",
     "example_en": "The zookeeper feeds the animals.", "example_cn": "动物园管理员喂动物。"},
    {"id": 369, "module": "五下7", "grade": "五年级", "word": "grass", "phonetic": "/ɡrɑːs/",
     "chinese": "草", "type": "noun",
     "example_en": "The horse eats grass.", "example_cn": "马吃草。"},
    {"id": 370, "module": "五下7", "grade": "五年级", "word": "keep", "phonetic": "/kiːp/",
     "chinese": "保持/养", "type": "verb",
     "example_en": "We should keep the zoo clean.", "example_cn": "我们应该保持动物园干净。"},

    # Module 8 - I'm going to buy a book
    {"id": 371, "module": "五下8", "grade": "五年级", "word": "bookshop", "phonetic": "/ˈbʊkʃɒp/",
     "chinese": "书店", "type": "place",
     "example_en": "I'm going to the bookshop.", "example_cn": "我要去书店。"},
    {"id": 372, "module": "五下8", "grade": "五年级", "word": "novel", "phonetic": "/ˈnɒvəl/",
     "chinese": "小说", "type": "noun",
     "example_en": "I am reading a novel.", "example_cn": "我在读一本小说。"},
    {"id": 373, "module": "五下8", "grade": "五年级", "word": "dictionary", "phonetic": "/ˈdɪkʃəneri/",
     "chinese": "词典", "type": "noun",
     "example_en": "I need an English dictionary.", "example_cn": "我需要一本英汉词典。"},

    # Module 9 - Are you going to run?
    {"id": 374, "module": "五下9", "grade": "五年级", "word": "run", "phonetic": "/rʌn/",
     "chinese": "跑/跑步", "type": "verb",
     "example_en": "Are you going to run tomorrow?", "example_cn": "你明天要去跑步吗？"},
    {"id": 375, "module": "五下9", "grade": "五年级", "word": "half", "phonetic": "/hɑːf/",
     "chinese": "一半", "type": "noun",
     "example_en": "I'm going to run for half an hour.", "example_cn": "我要跑半小时。"},
    {"id": 376, "module": "五下9", "grade": "五年级", "word": "hour", "phonetic": "/ˈaʊə/",
     "chinese": "小时", "type": "noun",
     "example_en": "There are 24 hours in a day.", "example_cn": "一天有24小时。"},
    {"id": 377, "module": "五下9", "grade": "五年级", "word": "tomorrow", "phonetic": "/təˈmɒrəʊ/",
     "chinese": "明天", "type": "time",
     "example_en": "I'll see you tomorrow.", "example_cn": "明天见。"},

    # Module 10 - The world is changing
    {"id": 378, "module": "五下10", "grade": "五年级", "word": "changing", "phonetic": "/ˈtʃeɪndʒɪŋ/",
     "chinese": "正在变化", "type": "verb",
     "example_en": "The world is changing.", "example_cn": "世界在变化。"},
    {"id": 379, "module": "五下10", "grade": "五年级", "word": "fast", "phonetic": "/fɑːst/",
     "chinese": "快的/快地", "type": "adjective/adverb",
     "example_en": "The world is changing fast.", "example_cn": "世界变化很快。"},
    {"id": 380, "module": "五下10", "grade": "五年级", "word": "life", "phonetic": "/laɪf/",
     "chinese": "生活", "type": "noun",
     "example_en": "Life is getting better.", "example_cn": "生活越来越好了。"},
    {"id": 381, "module": "五下10", "grade": "五年级", "word": "different", "phonetic": "/ˈdɪfərənt/",
     "chinese": "不同的", "type": "adjective",
     "example_en": "The world is different now.", "example_cn": "世界现在不一样了。"},
    {"id": 382, "module": "五下10", "grade": "五年级", "word": "interesting", "phonetic": "/ˈɪntrəstɪŋ/",
     "chinese": "有趣的", "type": "adjective",
     "example_en": "The world is very interesting.", "example_cn": "世界很有趣。"},
]

# ===== 合并所有年级的单词 =====
WORDS = WORDS_3 + WORDS_4 + WORDS_5


def get_words_by_module(module_name, grade=None):
    """按模块筛选，可指定年级"""
    result = [w for w in WORDS if w["module"] == module_name]
    if grade:
        result = [w for w in result if w.get("grade") == grade]
    return result


def search_words(keyword):
    """搜索单词"""
    kw = keyword.lower()
    return [w for w in WORDS
            if kw in w["word"].lower()
            or kw in w["chinese"]
            or kw in w.get("phonetic", "").lower()
            or kw in w.get("example_en", "").lower()]


def get_all_modules(grade=None):
    """获取所有模块列表，可按年级过滤"""
    modules = {}
    for w in WORDS:
        if grade and w.get("grade") != grade:
            continue
        mod = w["module"]
        if mod not in modules:
            modules[mod] = {"module": mod, "grade": w.get("grade", "三年级"), "count": 0}
        modules[mod]["count"] += 1
    return list(modules.values())


def get_all_grades():
    """获取所有年级列表"""
    grades = set()
    for w in WORDS:
        if w.get("grade"):
            grades.add(w["grade"])
    return sorted(grades)
